### ISSUE TITLE
Trigger rebuild with conda-build 2.0

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/ncurses-feedstock#25]
Dear Conda-Forge team,
in @bioconda we quite urgently need an updated ncurses with the longer prefixes. Can you trigger a rebuild?

Or should I do that using a pull request and increasing the build number?

Thanks,
Johannes

**Comment by jakirkham** [comment]
Would love to. Unfortunately we are blocked right now as `cmake` doesn't seem to run correctly with `conda-build` version `2`. Please see issue ( https://github.com/conda-forge/cmake-feedstock/issues/21 ) for more details.

**Comment by johanneskoester** [comment]
Thanks for the update. Strangely, cmake works fine for us on bioconda, but maybe we are pulling the version from the default channel. If I may ask, what is the purpose of rebuilding cmake in conda-forge?

**Comment by jakirkham** [comment]
Addressing the `conda-build` version `2.0.x` rebuild of `ncurses` in PR ( https://github.com/conda-forge/ncurses-feedstock/pull/26 ).

Also appears the `cmake` issues go away with `conda` version `4.2.x` instead of `4.1.x`. So we have gone ahead and upgraded to `conda` version `4.2.x`.

Both of these thanks to the hard work of @jjhelmus .

**Comment by johanneskoester** [comment]
Great, thanks!
